# Generated by Django 5.0.3 on 2024-05-05 09:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('birth_date', models.DateField()),
                ('position', models.CharField(choices=[('FE', 'Frontend-разработчик'), ('BE', 'Backend-разработчик'), ('AN', 'Аналитик'), ('MN', 'Менеджер'), ('DS', 'Дизайнер')], max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Мужчина'), ('F', 'Женщина')], max_length=50)),
                ('technology', models.CharField(choices=[('CS', 'C#'), ('RT', 'React'), ('JV', 'Java'), ('PH', 'PHP'), ('FG', 'Figma'), ('WD', 'Word')], max_length=50)),
            ],
        ),
    ]
